toolkit:
  project_id: 'PROJECTID'
  clone:
    asda_url: 'https://webgate.ec.europa.eu/fpfis/files-for/automate_dumps'
    dumpfile: 'dump.sql'
    config_file: 'config/sync/core.extension.yml'
  build:
    dist:
      root: 'dist'
      commands: []
    dev:
      commands: []
  git:
    user_name: 'Toolkit'
    user_email: 'digit-core@ec.europa.eu'
