toolkit:
  clone:
    asda_url: 'https://webgate.ec.europa.eu/fpfis/files-for/automate_dumps/'
    dumpfile: 'dump.sql'

command:
  toolkit:
    clone-site:
      options:
        uri: ${drupal.root}
        dumpfile: ${toolkit.clone.dumpfile}
