command:
  toolkit:
    install-dump:
      options:
        dumpfile: ${toolkit.clone.dumpfile}
    download-dump:
      options:
        asda-url: ${toolkit.clone.asda_url}
        asda-user: ${env.ASDA_USER}
        asda-password: ${env.ASDA_PASSWORD}
        dumpfile: ${toolkit.clone.dumpfile}
        project-id: ${toolkit.project_id}
    run-deploy:
      options:
        sequence-file: ${toolkit.deploy.sequence_file}
        sequence-key: ${toolkit.deploy.sequence_key}
        config-file: ${toolkit.deploy.config_file}
